#!/bin/bash -x

INRES="1920x1080"
OUTRES="1920x1080"
FPS="30"

ffmpeg -f x11grab -s "$INRES" -r "$FPS" -i :0.0  -f pulse -ac 2 -ar 48000 -i alsa_output.pci-0000_00_1f.3.analog-stereo.monitor -f pulse -ac 2 -ar 48000 -i alsa_input.pci-0000_00_1f.3.analog-stereo -filter_complex amix=inputs=2 \
-vcodec libx264 -s "$OUTRES" \
-acodec libmp3lame -ab 128k -ar 44100 \
-threads 0 -f flv $1
