#!/bin/bash

declare -a name="MD. Fahim Abrar Saikat"
declare -a mail="saikat.cucse.52@gmail.com"
declare -a ID="1935202534"
day=$(date +"%D, %r")

info=$(printf "@Author\t: ${name}\n@Mail\t: ${mail}\n@ID\t\t: ${ID}\n@Date\t: $day\n")

printf "Filename: " && read file
echo "${info}" > $file.c && nvim $file.c && exit 0
